steps:
# Step 0: Install test dependencies
- name: 'python:3.10-slim'
  entrypoint: '/bin/bash'
  args:
    - '-c'
    - |
      pip install --user -r docker/requirements-test.txt
  id: 'install-test-dependencies'

# Step 1: Check if pymongo is installed
- name: 'python:3.10-slim'
  entrypoint: '/bin/bash'
  args:
    - '-c'
    - |
      python -c "import pymongo"
  id: 'check-pymongo'

# Step 2: Run unit tests
- name: 'python:3.10-slim'
  entrypoint: '/bin/bash'
  args:
    - '-c'
    - |
      export TESTING=True
      python -m unittest docker/test.py
  id: 'run-tests'

# Step 3: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-image:latest', 'docker/']
  id: 'build-image'

# Step 4: Push the Docker image to Google Cloud Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-image:latest']
  id: 'push-image'

images:
- 'gcr.io/$PROJECT_ID/my-image:latest'